### ISSUE TITLE
Unto The End - CUSA25819

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [red-prig/fpps4-game-compatibility#1104] opened 2023-01-08 12:13 UTC
# Game name
Unto The End

## Code
CUSA25819

## Game version
1.00

## Used emulator's version
red-prig/fpPS4@14ada4d

## Current status
Boots

## Error
```
EAssertionFailed: VOP3a?344 (emit_vop3.pas, line 1122)
``` 

## Description
Boots with hacks

## Used hacks
`-h COMPUTE_DISABLE_HACK` - required to make game bootable

## Screenshots
![image](https://user-images.githubusercontent.com/24764335/211195399-bdc55616-ed65-44bd-b3c8-1da8de3bb647.png)

**Comment by ArbestRi** [comment] 2023-01-08 17:27
Retest, as re-prig added VOP3

**Comment by red-prig** [comment] 2023-01-08 17:28
@ArbestRi still not

**Comment by GamingDuckingalt** [comment] 2023-01-08 17:28
> Retest, as re-prig added VOP3

prig didn't add the VOP3?344

**Comment by Kimiegg** [comment] 2023-01-08 19:54
retest

**Comment by idk17roblox** [comment] 2023-01-08 20:19
Duplicate of https://github.com/red-prig/fpps4-game-compatibility/issues/288 btw

**Closed** 2023-01-09 02:38 UTC
Labels: status-boots, shader recompiler
