### ISSUE TITLE
Ghost of Tsushima DIRECTOR’S CUT

### ISSUE THREAD

**Issue by Chedark17** [red-prig/fpps4-game-compatibility#1801] opened 2024-01-03 22:08 UTC
### Game Name

Ghost of Tsushima DIRECTOR’S CUT

### Game code

CUSA11456

### Game version

undefined

### Used emulator's version

1.2.3

### Current status

Boots

### Error

says in the logs im missing this file:playgo-chunk.dat
when i try to lunch it just pull up a black screen with text.

### Description

dosnt work

### Screenshots

![image](https://github.com/red-prig/fpps4-game-compatibility/assets/155587790/327f290e-ac66-4998-8cf8-3a1d028057bd)
![image](https://github.com/red-prig/fpps4-game-compatibility/assets/155587790/2712e5d2-3bfa-4d1f-a870-317a04876668)

**Comment by red-prig** [comment] 2024-01-03 22:35
Firstly, the game was clearly unpacked incorrectly, secondly, it’s a duplicate of https://github.com/red-prig/fpps4-game-compatibility/issues/1641

**Closed as completed** 2024-01-03 22:36 UTC
Labels: duplicate, invalid
