### ISSUE TITLE
EA Sports UFC 4 - CUSA14209 

### ISSUE THREAD

**Issue by Jeffy101s** [red-prig/fpps4-game-compatibility#1455] opened 2023-03-25 01:05 UTC
### Game Name

EA SPORTS UFC 4

### Game code

CUSA14209

### Game version

04.02

### Used emulator's version

5fa656d

### Current status

Nothing

### Error

nop nid:libkernel:81E0DAAA01FD9538:scePthreadKeyCreate

### Description

Please fix this error I don’t feel like buying a ps4 nop nid:libkernel:81E0DAAA01FD9538:scePthreadKeyCreate

**Comment by ArbestRi** [comment] 2023-03-25 02:45
Duplicate of #418

**Closed** 2023-03-25 02:56 UTC
Labels: duplicate
