### ISSUE TITLE
Almost There: The Platformer - CUSA14287

### ISSUE THREAD

**Issue by gs-soda** [red-prig/fpps4-game-compatibility#835] opened 2023-01-02 15:55 UTC
# Game name
Almost There: The Platformer 

## Code
CUSA14287

## Game version
1.02

## Used emulator's version
red-prig/fpPS4@39a4e2c

## Current status
Boots

## Error
```
nop nid:libSceNpTus:D67FDD1AE9018276:sceNpTusCreateNpTitleCtxA 
``` 

## Description
Crashes at the menu

## Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/80367194/210254269-79e476c7-3edb-4c61-bc8a-cc75e5524f81.png)

**Comment by ArbestRi** [comment] 2023-01-02 16:26
Try using hacks

**Comment by ArbestRi** [comment] 2023-01-17 19:31
Can relate: gives error: nop nid:libSceNpTus:D67FDD1AE9018276:sceNpTusCreateNpTitleCtxA

**Comment by idk17roblox** [comment] 2023-01-20 16:53
Duplicate of https://github.com/red-prig/fpps4-game-compatibility/issues/509

**Closed** 2023-01-20 18:04 UTC
Labels: duplicate
